"""initial

Revision ID: a50f0648c822
Revises: 
Create Date: 2020-11-13 17:43:40.843226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50f0648c822'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('femodji', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq__tbl_types__fname'), ['fname'])
        batch_op.create_unique_constraint(batch_op.f('uq__tbl_types__id'), ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq__tbl_types__id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq__tbl_types__fname'), type_='unique')
        batch_op.drop_column('femodji')

    # ### end Alembic commands ###
